# Generated by Django 2.2.5 on 2019-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
