# Generated by Django 2.2.5 on 2019-09-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('short_desc', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('mrp', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(max_length=400)),
                ('product_url', models.CharField(max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=60)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='productpage',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Subcategory'),
        ),
    ]
