# Generated by Django 2.2.5 on 2019-09-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190925_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='product.ProductPage'),
            preserve_default=False,
        ),
    ]
