# Generated by Django 2.2.5 on 2019-09-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
