# Generated by Django 2.2.5 on 2019-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productpage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='instock',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
