# Generated by Django 2.2.5 on 2019-09-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productpage_instock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpage',
            old_name='instock',
            new_name='Status',
        ),
    ]
